/* SPDX-License-Identifier: MIT */
/*
 * Copyright © 2025 Intel Corporation
 */

#ifndef _XE_HW_ERROR_REGS_H_
#define _XE_HW_ERROR_REGS_H_

#define HEC_UNCORR_ERR_STATUS(base)                    XE_REG((base) + 0x118)
#define    UNCORR_FW_REPORTED_ERR                      BIT(6)

#define HEC_UNCORR_FW_ERR_DW0(base)                    XE_REG((base) + 0x124)

#define DEV_ERR_STAT_NONFATAL			0x100178
#define DEV_ERR_STAT_CORRECTABLE		0x10017c
#define DEV_ERR_STAT_REG(x)			XE_REG(_PICK_EVEN((x), \
								  DEV_ERR_STAT_CORRECTABLE, \
								  DEV_ERR_STAT_NONFATAL))
#define   XE_SGMI_DATA_PARITY_ERROR		BIT(25)
#define   XE_MERT_ERROR				BIT(20)
#define   XE_CSC_ERROR				BIT(17)
#define   XE_SOC_ERROR				BIT(16)
#define   XE_SGCI_DATA_PARITY_ERROR		BIT(13)
#define   XE_SGUNIT_ERROR			BIT(12)
#define   XE_SGLI_DATA_PARITY_ERROR		BIT(9)
#define   XE_GSC_ERROR				BIT(8)
#define   XE_SGDI_DATA_PARITY_ERROR		BIT(5)
#define   XE_DISPLAY_ERROR			BIT(4)
#define   XE_SGGI_DATA_PARITY_ERROR		BIT(1)
#define   XE_GT_ERROR				BIT(0)

#define DEV_ERR_STAT_NONFATAL_VALID_MASK \
	(XE_SGMI_DATA_PARITY_ERROR | XE_MERT_ERROR | XE_CSC_ERROR | XE_SOC_ERROR | \
	 XE_SGCI_DATA_PARITY_ERROR | XE_SGUNIT_ERROR | XE_SGLI_DATA_PARITY_ERROR | \
	 XE_GSC_ERROR | XE_SGDI_DATA_PARITY_ERROR | XE_DISPLAY_ERROR |	\
	 XE_SGGI_DATA_PARITY_ERROR | XE_GT_ERROR)

#define DEV_ERR_STAT_CORRECTABLE_VALID_MASK \
	(XE_CSC_ERROR | XE_SOC_ERROR | XE_SGUNIT_ERROR | XE_GSC_ERROR | \
	 XE_DISPLAY_ERROR | XE_GT_ERROR)

#endif
